### ISSUE TITLE
Decide on theme to use

### ISSUE THREAD

**Issue by athowes** [epinowcast/enwtheme#2]
We should pick a theme to use throughout the epinowcast community packages.

I think themes with dark code blocks are somewhat ugly (and possibly worse for eyes, comprehension, and reading ability -- can look for references if you'd like) and would prefer we move to something light.

* Dark code block example: https://package.epinowcast.org/articles/epinowcast.html
* Light code block example: https://hashprng.epinowcast.org/dev/articles/hashprng.html

**Comment by seabbs** [comment]
I don't have a strong opinion so happy to defer here. @pearsonca @adrian-lison @parksw3 @Bisaloo @sbfnk any views?

**Comment by pearsonca** [comment]
I mildly prefer the hashprng one - bit less jumping around in format, I guess? Though whenever given the option, I look at things in dark theme.

**Comment by seabbs** [comment]
Noting historically we used `preferably` which let you switch between dark and light themes but it was very unstable and I would rather not return to it

**Comment by Bisaloo** [comment]
If using a light theme, I agree it should probably have light code blocks. Dark code blocks seem distracting. I don't feel that strongly either though.

**Comment by seabbs** [comment]
> Light code block example: [hashprng.epinowcast.org/dev/articles/hashprng.html](https://hashprng.epinowcast.org/dev/articles/hashprng.html)

It sounds like this is everyone's mild preference with no strong voices against so we should go with this I think

**Comment by athowes** [comment]
> It sounds like this is everyone's mild preference with no strong voices against

Yes, agree, let's do it. I'll try making a PR today (I think it's a simple change)
